### PR TITLE
Added support for placeholders in replacement text/strings

### PR DESCRIPTION
**Pull request by jshenguru**
Based on discussion [here](https://github.com/caddyserver/replace-response/issues/26#issuecomment-2518534936).

### CODE REVIEW

**Comment by mholt** [comment]
This looks good IMO.

@icholy -- what do you think of the proposed changes or additions to the replace package? It keeps things efficient while making dynamic values possible.

(We can always maintain a fork, no big deal probably -- but it would be nice to mainline the changes upstream.)

**Comment by icholy** [comment]
@mholt I don't have the bandwidth to work on that library right now. But I trust your judgement so I've added you as a collaborator.

**Comment by mholt** [comment]
Thanks @icholy -- I accepted; though I may step down soon for the same reasons :sweat_smile: 

@jshenguru If you want to make a PR against the replace package I can review it too!

**Comment by jshenguru** [comment]
@mholt The PR is created. Please review.

**Pull request closed without merging**
